blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/cheeseprince/obd-gauge-cluster/discussions
    about: For questions and general discussion, please use Discussions.
